runtime: java11
api_version: 1
instance_class: B4
env_variables:
  SPRING_PROFILES_ACTIVE: "prod"
basic_scaling:
  max_instances: 2
  idle_timeout: 30m
handlers:
  - url: /.*
    script: auto
    secure: always
    redirect_http_response_code: 301